language: python
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5


# solution based on https://gist.github.com/dan-blanchard/7045057
# setup anaconda to install scipy and numpy easily and quickly
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - hash -r
    - conda update --yes conda
    # are not specific to using mini
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    # some useful libraries to compile numpy/scipy
    # - "sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - echo $TRAVIS_PYTHON_VERSION
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose pandas coverage biopython
  - pip install colorlog
  - pip install nose easydev bioservices
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:
  - python setup.py nosetests --with-coverage --cover-package biokit

after_success:
  coveralls
