language: python
matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4


# setup anaconda to install scipy and numpy easily and quickly
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    # the next couple of lines fix a crash with multiprocessing on Travis and
    # are not specific to using mini
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    # some useful libraries to compile numpy/scipy
    # - "sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - conda install --yes python=$TRAVIS_PYHTON_VERSION atlas numpy scipy matplotlib nose dateutil pandas coverage
  # coverage packages are elsewhere
  #- conda install --yes -c python-coveralls nose-cov
  - pip install nose easydev bioservices
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:  
  - python setup.py nosetests --with-coverage --cover-package biokit 

after_success:
  coveralls
