language: python
matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install nose matplotlib easydev pandas bioservices scipy
  - pip install nose coverage
  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:  
  - python setup.py nosetests --with-coverage --cover-package biokit

after_success:
  coveralls
